In [1]:
import pandas as pd
import numpy as np

from ast import literal_eval
import seaborn as sns
import matplotlib.pyplot as plt
from ast import literal_eval
from collections import defaultdict
import os
from tqdm import tqdm
from scipy.stats import entropy
%matplotlib inline

pd.set_option('display.max_columns', None)
from scipy.stats import spearmanr
import numpy as np

In [2]:
def get_annotated_corr(df, corr_method="spearman"):
    rho = df.corr(method=corr_method)
    pval =df.corr(method=lambda x, y: spearmanr(x, y)[1]) - np.eye(*rho.shape)
    p = pval.applymap(lambda x: ''.join(['*' for t in [.05, .01, .001] if x <= t]))
    # Combine rho (correlation coefficients) and p-values (significance stars)
    annotated = rho.round(2).astype(str) + p
    # Create a mask for the upper triangle and diagonal
    mask = np.triu(np.ones_like(rho, dtype=bool))

    # Mask the upper triangle of the annotated DataFrame
    annotated = annotated.mask(mask)
    return annotated

In [ ]:
# all, crosslingual , monolingual

# ALL at line and word level

In [8]:
df_all_line_train = pd.read_csv("../results/inversion_language_confusion/line_level/dataframes/multi_line_all_weighted_entropy_bleu_score_for_train.csv")
df_all_word_train = pd.read_csv("../results/inversion_language_confusion/word_level/dataframes/multi_word_all_weighted_entropy_bleu_score_for_train.csv")

In [9]:
df_all_line_train.rename(columns={"entropy":"line_entropy"}, inplace=True)
df_all_word_train.rename(columns={"entropy":"word_entropy"}, inplace=True)

In [10]:
df_all_line_train.head(2)

   Unnamed: 0 lang  step  line_entropy language  inversion_avg   mt5
0           0  pan  Base      0.288206  Punjabi       6.765988  0.37
1           1  heb  Base      0.323412   Hebrew       6.011234  1.06

In [11]:
len(df_all_line_train), len(df_all_word_train)

(93, 93)

In [12]:
df_all=df_all_line_train.merge(df_all_word_train, on=["lang", "step", "language", "inversion_avg", "mt5"])[["line_entropy", "word_entropy", "inversion_avg", "mt5"]]

In [13]:
get_annotated_corr(df_all)

/var/folders/bj/qp6k2wl11h5gpn8j4hg0tgf40000gn/T/ipykernel_25613/1944174085.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  p = pval.applymap(lambda x: ''.join(['*' for t in [.05, .01, .001] if x <= t]))

              line_entropy word_entropy inversion_avg  mt5
line_entropy           NaN          NaN           NaN  NaN
word_entropy       0.93***          NaN           NaN  NaN
inversion_avg      0.66***      0.71***           NaN  NaN
mt5                   0.32         0.24          0.09  NaN

# crosslingual at line and word level

In [14]:
df_cross_line_train = pd.read_csv("../results/inversion_language_confusion/line_level/dataframes/multi_line_crosslingual_weighted_entropy_bleu_score_for_train.csv")
df_cross_word_train = pd.read_csv("../results/inversion_language_confusion/word_level/dataframes/multi_word_crosslingual_weighted_entropy_bleu_score_for_train.csv")

In [15]:
df_cross_line_train.rename(columns={"entropy":"line_entropy"}, inplace=True)
df_cross_word_train.rename(columns={"entropy":"word_entropy"}, inplace=True)

In [16]:
df_cross_word_train.head(2)

   Unnamed: 0 lang  step  word_entropy language  inversion_avg   mt5
0           0  pan  Base      0.782062  Punjabi       6.765988  0.37
1           1  heb  Base      0.844523   Hebrew       6.011234  1.06

In [17]:
len(df_cross_line_train), len(df_cross_word_train)

(93, 93)

In [18]:
df_cross=df_cross_line_train.merge(df_cross_word_train, on=["lang", "step", "language", "inversion_avg", "mt5"])[["line_entropy", "word_entropy", "inversion_avg", "mt5"]]

In [19]:
get_annotated_corr(df_cross)

/var/folders/bj/qp6k2wl11h5gpn8j4hg0tgf40000gn/T/ipykernel_25613/1944174085.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  p = pval.applymap(lambda x: ''.join(['*' for t in [.05, .01, .001] if x <= t]))

              line_entropy word_entropy inversion_avg  mt5
line_entropy           NaN          NaN           NaN  NaN
word_entropy       0.93***          NaN           NaN  NaN
inversion_avg      0.66***      0.71***           NaN  NaN
mt5                   0.32         0.23          0.09  NaN

# Monolingual

In [20]:
df_mono_line_train = pd.read_csv("../results/inversion_language_confusion/line_level/dataframes/multi_line_monolingual_weighted_entropy_bleu_score_for_train.csv")
df_mono_word_train = pd.read_csv("../results/inversion_language_confusion/word_level/dataframes/multi_word_monolingual_weighted_entropy_bleu_score_for_train.csv")

In [21]:
df_mono_line_train.rename(columns={"entropy":"line_entropy"}, inplace=True)
df_mono_word_train.rename(columns={"entropy":"word_entropy"}, inplace=True)

In [22]:
df_mono_line_train.head(2)

   Unnamed: 0 lang  step  line_entropy language  inversion_avg   mt5
0           0  cmn  Base           0.0  Chinese       6.385944  1.67
1           1  deu  Base           0.0   German       6.507209  3.05

In [24]:
df_mono= df_mono_line_train.merge(df_mono_word_train, on=["lang", "step", "language", "inversion_avg", "mt5"])[["line_entropy", "word_entropy", "inversion_avg", "mt5"]]

In [25]:
get_annotated_corr(df_mono)

/var/folders/bj/qp6k2wl11h5gpn8j4hg0tgf40000gn/T/ipykernel_25613/1944174085.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  p = pval.applymap(lambda x: ''.join(['*' for t in [.05, .01, .001] if x <= t]))

              line_entropy word_entropy inversion_avg  mt5
line_entropy           NaN          NaN           NaN  NaN
word_entropy       0.63***          NaN           NaN  NaN
inversion_avg      0.37***       0.33**           NaN  NaN
mt5                   0.05        0.42*          0.09  NaN

In [21]:
df_cross_line_eval = pd.read_csv("../results/inversion_language_confusion/line_level/dataframes/multi_line_crosslingual_weighted_entropy_bleu_score_for_eval.csv")
df_mono_line_eval = pd.read_csv("../results/inversion_language_confusion/line_level/dataframes/multi_line_crosslingual_weighted_entropy_bleu_score_for_eval.csv")
df_all_line_eval = pd.read_csv("../results/inversion_language_confusion/line_level/dataframes/multi_line_crosslingual_weighted_entropy_bleu_score_for_eval.csv")


df_cross_line_train = pd.read_csv("../results/inversion_language_confusion/line_level/dataframes/multi_line_crosslingual_weighted_entropy_bleu_score_for_train.csv")

In [22]:
df_line_eval

    Unnamed: 0 lang           step   entropy     language  inversion_avg   mt5
0            0  sin           Base  0.906096      Sinhala       6.614690  0.41
1            1  guj           Base  0.937231     Gujarati       8.875215  0.43
2            2  mhr           Base  1.189543  Meadow Mari       6.867405  0.00
3            3  pan           Base  1.288553      Punjabi      11.736179  0.37
4            4  amh           Base  1.294869      Amharic       7.261268  0.29
5            5  urd           Base  1.326647         Urdu       8.633891  0.61
6            6  kor           Base  1.491685       Korean       5.557817  1.14
7            7  ydd           Base  1.521591      Yiddish       6.548603  0.28
8            8  mon           Base  1.622283    Mongolian       7.952315  0.62
9            9  hin           Base  2.004991        Hindi       8.527334  1.21
10          10  arb           Base  2.193108       Arabic       6.145494  1.66
11          11  kaz           Base  2.279593       Kazakh      10.814507  0.65
12          12  heb           Base  2.817390       Hebrew       5.931228  1.06
13          13  cmn           Base  2.871821      Chinese       6.461958  1.67
14          14  mlt           Base  3.005896      Maltese       6.777715  0.64
15          15  jpn           Base  3.254513     Japanese       5.711295  1.92
16          16  deu           Base  3.276394       German       6.367758  3.05
17          17  tur           Base  3.893881      Turkish       7.978906  1.93
18          18  fin           Base  4.369611      Finnish       5.287667  1.35
19          19  hun           Base  4.411870    Hungarian       5.168398  1.48
20          20  sin          Step1  1.141209      Sinhala       6.182232  0.41
21          21  guj          Step1  1.409248     Gujarati       8.715326  0.43
22          22  mhr          Step1  1.345235  Meadow Mari       6.318067  0.00
23          23  pan          Step1  1.087947      Punjabi       9.702693  0.37
24          24  amh          Step1  1.142023      Amharic       6.739298  0.29
25          25  urd          Step1  1.487005         Urdu       8.214278  0.61
26          26  kor          Step1  1.631087       Korean       5.137799  1.14
27          27  ydd          Step1  1.691235      Yiddish       6.066991  0.28
28          28  mon          Step1  1.317206    Mongolian       7.791559  0.62
29          29  hin          Step1  1.943199        Hindi       8.591156  1.21
30          30  arb          Step1  1.708271       Arabic       5.962039  1.66
31          31  kaz          Step1  1.806291       Kazakh      10.842099  0.65
32          32  heb          Step1  2.371540       Hebrew       5.649249  1.06
33          33  cmn          Step1  1.970812      Chinese       5.692342  1.67
34          34  mlt          Step1  3.545577      Maltese       6.104905  0.64
35          35  jpn          Step1  2.634454     Japanese       5.201407  1.92
36          36  deu          Step1  3.804063       German       6.386494  3.05
37          37  tur          Step1  2.784181      Turkish       8.382994  1.93
38          38  fin          Step1  3.653262      Finnish       4.887594  1.35
39          39  hun          Step1  3.659523    Hungarian       4.741790  1.48
40          40  sin  Step50+sbeam8  1.321334      Sinhala       6.151704  0.41
41          41  guj  Step50+sbeam8  1.382066     Gujarati      10.098867  0.43
42          42  mhr  Step50+sbeam8  1.433262  Meadow Mari       6.074385  0.00
43          43  pan  Step50+sbeam8  0.804930      Punjabi      11.494145  0.37
44          44  amh  Step50+sbeam8  1.254834      Amharic       6.514071  0.29
45          45  urd  Step50+sbeam8  1.584389         Urdu       8.937319  0.61
46          46  kor  Step50+sbeam8  1.684488       Korean       4.956127  1.14
47          47  ydd  Step50+sbeam8  1.595596      Yiddish       5.947973  0.28
48          48  mon  Step50+sbeam8  1.410475    Mongolian       8.495218  0.62
49          49  hin  Step50+sbeam8  1.469653        Hindi       9.681111  1.21
50          50  arb  Step50+sbeam8  1.640628       Arabic       6.190297  1.66
51          51  kaz  Step50+sbeam8  1.806540       Kazakh      12.486366  0.65
52          52  heb  Step50+sbeam8  2.031384       Hebrew       5.741312  1.06
53          53  cmn  Step50+sbeam8  1.936300      Chinese       5.391864  1.67
54          54  mlt  Step50+sbeam8  3.304845      Maltese       5.899118  0.64
55          55  jpn  Step50+sbeam8  2.342637     Japanese       5.041052  1.92
56          56  deu  Step50+sbeam8  3.391187       German       6.833382  3.05
57          57  tur  Step50+sbeam8  2.852117      Turkish       9.699741  1.93
58          58  fin  Step50+sbeam8  3.693879      Finnish       4.759333  1.35
59          59  hun  Step50+sbeam8  3.381239    Hungarian       4.617942  1.48

# Inversion only look at monolingual and in-family training results
# it should have better corrolation

In [19]:
df = pd.read_csv("../datasets/prompts_language_confusion/results/reweighted_entropy_passrates.csv")

In [20]:
df

,LLM,source,lang,task,avg_line_weighted_entropy,avg_word_weighted_entropy,lpr,wpr
0,command-r,aya-human-annotated,ara,monolingual,0.000000,0.178040,NaN,NaN
1,command-r,aya-human-annotated,eng,monolingual,0.010732,0.293924,NaN,NaN
2,command-r,aya-human-annotated,por,monolingual,0.012451,1.009851,NaN,NaN
3,command-r,aya-human-annotated,tur,monolingual,0.004185,0.544514,NaN,NaN
4,command-r,aya-human-annotated,zho,monolingual,0.000000,0.320977,NaN,NaN
...,...,...,...,...,...,...,...,...
655,mistral-large,sharegpt,rus,crosslingual,0.138739,0.779244,0.65,0.91
656,mistral-large,sharegpt,spa,crosslingual,0.239500,1.232578,0.63,NaN
657,mistral-large,sharegpt,tur,crosslingual,0.165598,0.748824,0.67,NaN
658,mistral-large,sharegpt,vie,crosslingual,0.155959,0.655651,0.57,NaN
659,mistral-large,sharegpt,zho,crosslingual,0.310674,1.396946,0.43,1.00

In [4]:
df = pd.read_csv("../results/inversion_language_confusion/line_level/dataframes/multi_line_crosslingual_weighted_entropy.csv")

In [9]:
langs =['pan', 'heb', 'guj', 'cmn', 'deu', 'kaz', 'urd', 'jpn',
     'tur', 'hin', 'arb', 'mon', 'hin_pan', 'pan_urd', 'kaz_tur',
     'guj_hin', 'deu_tur', 'guj_urd', 'hin_urd', 'arb_heb', 'guj_pan',
     'kaz_mon', 'guj_tur', 'cmn_jpn', 'pan_tur', 'hin_tur', 'kaz_pan']

In [11]:
df["training_langs"] = df["training_langs"].apply(literal_eval)

In [13]:
df["train_langs"]=df["training_langs"].apply(lambda x:"_".join(x))

In [15]:
df = df[df["train_langs"].isin(langs)]

In [18]:
df

,Unnamed: 0,model,training,eval_lang,step,pred_langs,emb_cos_sim,training_langs,train_eval_langs,eval_in_training,pred_langs_dist,weighted_entropy,train_langs
0,694,me5_arb_Arab,['arb_Arab'],amh,Base,"{'eng': 0.07, 'ara': 0.77, 'fra': 0.1, 'deu': ...",0.788960,[arb],arb_amh,False,"{'eng': 0.07, 'ara': 0.77, 'fra': 0.1, 'deu': ...",0.861009,arb
1,695,me5_arb_Arab,['arb_Arab'],amh,Step1,"{'ara': 0.82, 'fra': 0.08, 'eng': 0.05, 'tur':...",0.792269,[arb],arb_amh,False,"{'ara': 0.82, 'fra': 0.08, 'eng': 0.05, 'tur':...",0.689381,arb
2,696,me5_arb_Arab,['arb_Arab'],amh,Step50+sbeam8,"{'ara': 0.82, 'fra': 0.06, 'eng': 0.05, 'tur':...",0.797702,[arb],arb_amh,False,"{'ara': 0.82, 'fra': 0.06, 'eng': 0.05, 'tur':...",0.696177,arb
3,730,me5_arb_Arab,['arb_Arab'],cmn,Base,"{'zho': 0.75, 'fas': 0.01, 'ara': 0.1, 'eng': ...",0.899977,[arb],arb_cmn,False,"{'zho': 0.75, 'fas': 0.01, 'ara': 0.1, 'eng': ...",0.914988,arb
4,731,me5_arb_Arab,['arb_Arab'],cmn,Step1,"{'ara': 0.63, 'tgl': 0.01, 'zho': 0.17, 'eng':...",0.820613,[arb],arb_cmn,False,"{'ara': 0.63, 'tgl': 0.01, 'zho': 0.17, 'eng':...",1.113367,arb
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1672,365,me5_urd_Arab,['urd_Arab'],tur,Step50+sbeam8,"{'eng': 0.2, 'urd': 0.71, 'fas': 0.01, 'unk': ...",0.876402,[urd],urd_tur,False,"{'eng': 0.2, 'urd': 0.71, 'fas': 0.01, 'unk': ...",0.669320,urd
1673,366,me5_urd_Arab,['urd_Arab'],tur,Base,"{'urd': 0.74, 'tur': 0.01, 'pnb': 0.01, 'eng':...",0.869960,[urd],urd_tur,False,"{'urd': 0.74, 'tur': 0.01, 'pnb': 0.01, 'eng':...",5.182434,urd
1674,324,me5_urd_Arab,['urd_Arab'],ydd,Step1,"{'urd': 0.97, 'eng': 0.02, 'fas': 0.01}",0.874004,[urd],urd_ydd,False,"{'urd': 0.97, 'eng': 0.02, 'fas': 0.01}",0.125206,urd
1675,325,me5_urd_Arab,['urd_Arab'],ydd,Step50+sbeam8,"{'urd': 0.94, 'eng': 0.01, 'fas': 0.02, 'pnb':...",0.845068,[urd],urd_ydd,False,"{'urd': 0.94, 'eng': 0.01, 'fas': 0.02, 'pnb':...",0.266160,urd
1676,326,me5_urd_Arab,['urd_Arab'],ydd,Base,"{'urd': 0.95, 'fas': 0.02, 'ara': 0.01, 'eng':...",0.879725,[urd],urd_ydd,False,"{'urd': 0.95, 'fas': 0.02, 'ara': 0.01, 'eng':...",0.218960,urd